---
- apt: pkg={{item}} state=installed
  with_items:
    - curl
    - node
    - nodejs

- file: path=/root/.ssh state=directory
- copy: src=.ssh/config mode=600 dest=/root/.ssh/config

- authorized_key: user=root
                  key="{{ item }}"
  with_file:
    - public_keys/matt_booth_ubuntu_laptop
    - public_keys/paul_clegg
    - public_keys/tomcat
