---
- apt: pkg={{item}} state=installed
  with_items:
    - curl
    - node
    - nodejs
    - apache2
    - libapache2-mod-php5
    - mysql-server-5.6
    - fail2ban
    - python-mysqldb
    - php5-curl
    - php5-gd
    - php5-mysql

- file: path=/ubuntu/.ssh state=directory
- copy: src=.ssh/config mode=600 dest=/ubuntu/.ssh/config
- copy: src=hosts dest=/etc/hosts
- copy: src=hostname dest=/etc/hostname

- authorized_key: user=ubuntu
                  key="{{ item }}"
  with_file:
    - public_keys/matt_booth_ubuntu_laptop
    - public_keys/paul_clegg
    - public_keys/tomcat

- include: copy_files.yml
- include: create_database.yml
- include: apache.yml
