---
- name: Add php5.5 repo
   apt_repository: repo=ppa:ondrej/php5-5.6 state='present' update_cache=yes
   when: "php_min_version == 5.6"

- apt: pkg={{item}} state=installed
  with_items:
    - php5-cli
    - php5-fpm
    - php5-mysql
    - php5-curl
    - php5-mcrypt
    - php5-gd
    - curl
    - node
    - nodejs
    - apache2
    - libapache2-mod-php5
    - mysql-server-5.6
    - fail2ban
    - python-mysqldb

- file: path=/ubuntu/.ssh state=directory
- copy: src=.ssh/config mode=600 dest=/ubuntu/.ssh/config
- copy: src=hosts dest=/etc/hosts
- copy: src=hostname dest=/etc/hostname

- authorized_key: user=ubuntu
                  key="{{ item }}"
  with_file:
    - public_keys/matt_booth_ubuntu_laptop
    - public_keys/paul_clegg
    - public_keys/tomcat

- include: copy_files.yml
- include: create_database.yml
- include: apache.yml
